import { Category, Product, normalize } from './domain';
import { productLabel } from './i18n';
export const categories: { id: Category; name: string; emoji: string; color: string }[] = [
  { id: 'fresh', name: 'Fruta y verdura', emoji: '🥑', color: '#E3EEDD' },
  { id: 'dairy', name: 'Lácteos y huevos', emoji: '🥛', color: '#E5EDF3' },
  { id: 'bakery', name: 'Panadería', emoji: '🥖', color: '#F5E9CE' },
  { id: 'pantry', name: 'Despensa', emoji: '🫙', color: '#EEE5D9' },
  { id: 'protein', name: 'Carne y pescado', emoji: '🐟', color: '#F8E3DC' },
  { id: 'frozen', name: 'Congelados', emoji: '🧊', color: '#E2ECF7' },
  { id: 'drinks', name: 'Bebidas', emoji: '🧃', color: '#EEE5F2' },
  { id: 'home', name: 'Hogar y cuidado', emoji: '🧼', color: '#E2EEE9' },
  { id: 'other', name: 'Otros', emoji: '🛍️', color: '#EFECE6' },
];
const group = (category: Category, entries: [string, string, string?][]): Product[] =>
  entries.map(([name, emoji, unit]) => ({
    name,
    catalogId: name,
    emoji,
    category,
    unit: unit || 'ud',
  }));
const pastaTypes = [
  'Espaguetis',
  'Macarrones',
  'Tallarines',
  'Espirales de pasta',
  'Lacitos de pasta',
  'Rigatoni',
  'Raviolis',
  'Tortellini',
  'Ñoquis',
  'Placas de lasaña',
  'Placas de canelones',
  'Pasta integral',
];
export const matchesProductSearch = (product: Product, query: string) =>
  normalize(
    productLabel(product) +
      (product.catalogId && pastaTypes.includes(product.catalogId) ? ' pasta' : ''),
  ).includes(normalize(query));
export const products: Product[] = [
  ...group('fresh', [
    ['Aguacate', '🥑'],
    ['Tomates', '🍅', 'kg'],
    ['Plátanos', '🍌'],
    ['Manzanas', '🍎', 'kg'],
    ['Limones', '🍋'],
    ['Zanahorias', '🥕', 'kg'],
    ['Brócoli', '🥦'],
    ['Lechuga', '🥬'],
    ['Patatas', '🥔', 'kg'],
    ['Cebollas', '🧅', 'kg'],
    ['Fresas', '🍓', 'bandeja'],
    ['Naranjas', '🍊', 'kg'],
    ['Uvas', '🍇', 'kg'],
    ['Pepino', '🥒'],
    ['Pimientos', '🫑'],
    ['Ajo', '🧄'],
    ['Calabacín', '🥒'],
    ['Espinacas', '🥬', 'bolsa'],
    ['Champiñones', '🍄', 'bandeja'],
    ['Pera', '🍐'],
    ['Sandía', '🍉'],
    ['Piña', '🍍'],
    ['Melocotón', '🍑'],
    ['Mandarinas', '🍊', 'kg'],
    ['Kiwi', '🥝', 'ud'],
    ['Melón', '🍈', 'ud'],
    ['Mango', '🥭', 'ud'],
    ['Arándanos', '🫐', 'bandeja'],
    ['Frambuesas', '🫐', 'bandeja'],
    ['Cerezas', '🍒', 'kg'],
    ['Ciruelas', '🍑', 'kg'],
    ['Pomelo', '🍊', 'ud'],
    ['Limas', '🍋', 'ud'],
    ['Berenjena', '🍆', 'ud'],
    ['Coliflor', '🥦', 'ud'],
    ['Calabaza', '🎃', 'kg'],
    ['Boniato', '🍠', 'kg'],
    ['Puerros', '🥬', 'ud'],
    ['Apio', '🥬', 'ud'],
    ['Judías verdes', '🫛', 'kg'],
    ['Espárragos', '🌱', 'manojo'],
    ['Alcachofas', '🌱', 'kg'],
    ['Repollo', '🥬', 'ud'],
    ['Rúcula', '🥬', 'bolsa'],
    ['Ensalada mezclum', '🥬', 'bolsa'],
    ['Remolacha', '🥬', 'paquete'],
    ['Jengibre', '🫚', 'ud'],
    ['Perejil', '🌿', 'manojo'],
    ['Cilantro', '🌿', 'manojo'],
    ['Albahaca', '🌿', 'manojo'],
  ]),
  ...group('dairy', [
    ['Leche', '🥛', 'L'],
    ['Huevos', '🥚', 'docena'],
    ['Yogur natural', '🥣', 'pack'],
    ['Queso', '🧀'],
    ['Mantequilla', '🧈'],
    ['Bebida de avena', '🥛', 'L'],
    ['Nata', '🥛', 'brik'],
    ['Mozzarella', '🧀'],
    ['Leche sin lactosa', '🥛', 'L'],
    ['Leche desnatada', '🥛', 'L'],
    ['Leche semidesnatada', '🥛', 'L'],
    ['Bebida de soja', '🥛', 'L'],
    ['Bebida de almendra', '🥛', 'L'],
    ['Yogur griego', '🥣', 'pack'],
    ['Yogur vegetal', '🥣', 'pack'],
    ['Kéfir', '🥛', 'botella'],
    ['Queso rallado', '🧀', 'bolsa'],
    ['Queso en lonchas', '🧀', 'paquete'],
    ['Queso fresco', '🧀', 'pack'],
    ['Queso crema', '🧀', 'ud'],
    ['Parmesano', '🧀', 'ud'],
    ['Margarina', '🧈', 'ud'],
  ]),
  ...group('bakery', [
    ['Pan', '🥖'],
    ['Pan de molde', '🍞', 'paquete'],
    ['Croissant', '🥐'],
    ['Tortillas de trigo', '🫓', 'paquete'],
    ['Tostadas', '🍞', 'paquete'],
    ['Pan integral', '🍞', 'ud'],
    ['Pan sin gluten', '🍞', 'paquete'],
    ['Pan de hamburguesa', '🍔', 'paquete'],
    ['Pan de pita', '🫓', 'paquete'],
    ['Tortillas de maíz', '🫓', 'paquete'],
    ['Masa de pizza', '🍕', 'ud'],
    ['Hojaldre', '🥐', 'paquete'],
    ['Magdalenas', '🧁', 'paquete'],
  ]),
  ...group('pantry', [
    ['Arroz', '🍚', 'kg'],
    ['Pasta', '🍝', 'paquete'],
    ...pastaTypes.map((name): [string, string, string] => [name, '🍝', 'paquete']),
    ['Aceite de oliva', '🫒', 'L'],
    ['Café', '☕', 'paquete'],
    ['Avena', '🥣', 'paquete'],
    ['Lentejas', '🫘', 'bote'],
    ['Garbanzos', '🫘', 'bote'],
    ['Tomate frito', '🥫', 'bote'],
    ['Atún en lata', '🥫', 'pack'],
    ['Sal', '🧂', 'kg'],
    ['Azúcar', '🧂', 'kg'],
    ['Harina', '🌾', 'kg'],
    ['Chocolate', '🍫'],
    ['Galletas', '🍪', 'paquete'],
    ['Frutos secos', '🥜', 'bolsa'],
    ['Miel', '🍯', 'bote'],
    ['Vinagre', '🍾'],
    ['Cereales', '🥣', 'caja'],
    ['Alubias blancas', '🫘', 'bote'],
    ['Alubias rojas', '🫘', 'bote'],
    ['Quinoa', '🌾', 'paquete'],
    ['Cuscús', '🌾', 'paquete'],
    ['Pasta sin gluten', '🍝', 'paquete'],
    ['Fideos', '🍜', 'paquete'],
    ['Aceite de girasol', '🌻', 'L'],
    ['Tomate triturado', '🥫', 'bote'],
    ['Maíz en conserva', '🌽', 'lata'],
    ['Sardinas en lata', '🥫', 'lata'],
    ['Aceitunas', '🫒', 'bote'],
    ['Pepinillos', '🥒', 'bote'],
    ['Caldo de verduras', '🥣', 'brik'],
    ['Caldo de pollo', '🥣', 'brik'],
    ['Leche de coco', '🥥', 'lata'],
    ['Crema de verduras', '🥣', 'brik'],
    ['Gazpacho', '🍅', 'brik'],
    ['Hummus', '🫘', 'ud'],
    ['Mayonesa', '🥫', 'bote'],
    ['Kétchup', '🍅', 'botella'],
    ['Mostaza', '🫙', 'bote'],
    ['Salsa de soja', '🍾', 'botella'],
    ['Pesto', '🌿', 'bote'],
    ['Pimienta negra', '🧂', 'bote'],
    ['Pimentón', '🌶️', 'bote'],
    ['Orégano', '🌿', 'bote'],
    ['Comino', '🧂', 'bote'],
    ['Curry', '🧂', 'bote'],
    ['Canela', '🧂', 'bote'],
    ['Laurel', '🌿', 'bolsa'],
    ['Levadura de panadería', '🍞', 'paquete'],
    ['Levadura química', '🧁', 'bote'],
    ['Bicarbonato alimentario', '🧂', 'bote'],
    ['Pan rallado', '🍞', 'paquete'],
    ['Maicena', '🌽', 'paquete'],
    ['Mermelada', '🍓', 'bote'],
    ['Crema de cacahuete', '🥜', 'bote'],
    ['Cacao en polvo', '🍫', 'bote'],
    ['Patatas fritas de bolsa', '🥔', 'bolsa'],
    ['Palomitas', '🍿', 'paquete'],
    ['Tortitas de arroz', '🍘', 'paquete'],
    ['Pasas', '🍇', 'bolsa'],
    ['Dátiles', '🌴', 'paquete'],
    ['Semillas de chía', '🌱', 'bolsa'],
  ]),
  ...group('protein', [
    ['Pollo', '🍗', 'kg'],
    ['Salmón', '🐟', 'bandeja'],
    ['Carne picada', '🥩', 'bandeja'],
    ['Jamón', '🥓', 'paquete'],
    ['Tofu', '🧈'],
    ['Merluza', '🐟', 'kg'],
    ['Pavo', '🍗', 'paquete'],
    ['Ternera', '🥩', 'kg'],
    ['Lomo de cerdo', '🥩', 'kg'],
    ['Costillas', '🍖', 'kg'],
    ['Cordero', '🍖', 'kg'],
    ['Pechuga de pollo', '🍗', 'kg'],
    ['Hamburguesas', '🍔', 'bandeja'],
    ['Salchichas', '🌭', 'paquete'],
    ['Bacon', '🥓', 'paquete'],
    ['Jamón cocido', '🥓', 'paquete'],
    ['Chorizo', '🥓', 'ud'],
    ['Bacalao', '🐟', 'kg'],
    ['Dorada', '🐟', 'ud'],
    ['Lubina', '🐟', 'ud'],
    ['Gambas', '🦐', 'kg'],
    ['Mejillones', '🦪', 'kg'],
    ['Calamares', '🦑', 'kg'],
    ['Tempeh', '🫘', 'paquete'],
    ['Hamburguesas vegetales', '🍔', 'paquete'],
  ]),
  ...group('frozen', [
    ['Guisantes', '🫛', 'bolsa'],
    ['Helado', '🍦'],
    ['Pizza', '🍕'],
    ['Verduras congeladas', '🥦', 'bolsa'],
    ['Patatas para freír congeladas', '🍟', 'bolsa'],
    ['Croquetas congeladas', '🥟', 'bolsa'],
    ['Pescado congelado', '🐟', 'bolsa'],
    ['Gambas congeladas', '🦐', 'bolsa'],
    ['Frutos rojos congelados', '🫐', 'bolsa'],
    ['Espinacas congeladas', '🥬', 'bolsa'],
    ['Nuggets de pollo', '🍗', 'bolsa'],
    ['Hielo', '🧊', 'bolsa'],
  ]),
  ...group('drinks', [
    ['Agua', '💧', 'L'],
    ['Zumo', '🧃', 'L'],
    ['Té', '🍵', 'caja'],
    ['Agua con gas', '🫧', 'botella'],
    ['Refresco de cola', '🥤', 'botella'],
    ['Refresco de limón', '🥤', 'botella'],
    ['Cerveza', '🍺', 'pack'],
    ['Cerveza sin alcohol', '🍺', 'pack'],
    ['Vino tinto', '🍷', 'botella'],
    ['Vino blanco', '🍾', 'botella'],
    ['Infusiones', '🍵', 'caja'],
    ['Café descafeinado', '☕', 'paquete'],
    ['Café soluble', '☕', 'bote'],
    ['Cápsulas de café', '☕', 'caja'],
    ['Batido', '🥤', 'brik'],
  ]),
  ...group('home', [
    ['Papel higiénico', '🧻', 'pack'],
    ['Detergente', '🧴'],
    ['Lavavajillas', '🧽'],
    ['Bolsas de basura', '🗑️', 'rollo'],
    ['Champú', '🧴'],
    ['Gel de ducha', '🧼'],
    ['Pasta de dientes', '🪥'],
    ['Papel de cocina', '🧻', 'pack'],
    ['Comida para gato', '🐈', 'bolsa'],
    ['Comida para perro', '🐕', 'bolsa'],
    ['Suavizante', '🧴', 'botella'],
    ['Quitamanchas', '🧴', 'botella'],
    ['Pastillas de lavavajillas', '🧽', 'caja'],
    ['Sal para lavavajillas', '🧂', 'kg'],
    ['Abrillantador de lavavajillas', '🧴', 'botella'],
    ['Lejía', '🧴', 'botella'],
    ['Limpiador multiusos', '🧴', 'botella'],
    ['Limpiacristales', '🪟', 'botella'],
    ['Friegasuelos', '🪣', 'botella'],
    ['Limpiador de WC', '🚽', 'botella'],
    ['Estropajos', '🧽', 'pack'],
    ['Bayetas', '🧽', 'pack'],
    ['Guantes de limpieza', '🧤', 'par'],
    ['Papel de aluminio', '🧻', 'rollo'],
    ['Film transparente', '🧻', 'rollo'],
    ['Papel de horno', '🧻', 'rollo'],
    ['Bolsas de congelación', '🧊', 'caja'],
    ['Servilletas', '🧻', 'paquete'],
    ['Pañuelos de papel', '🧻', 'pack'],
    ['Jabón de manos', '🧼', 'botella'],
    ['Acondicionador', '🧴', 'botella'],
    ['Desodorante', '🧴', 'ud'],
    ['Cepillo de dientes', '🪥', 'ud'],
    ['Hilo dental', '🦷', 'ud'],
    ['Enjuague bucal', '🦷', 'botella'],
    ['Crema hidratante', '🧴', 'ud'],
    ['Protector solar', '☀️', 'ud'],
    ['Maquinillas de afeitar', '🪒', 'pack'],
    ['Espuma de afeitar', '🪒', 'ud'],
    ['Compresas', '🩹', 'paquete'],
    ['Tampones', '🩹', 'caja'],
    ['Salvaslips', '🩹', 'paquete'],
    ['Discos de algodón', '☁️', 'paquete'],
    ['Bastoncillos', '☁️', 'caja'],
    ['Pañales', '👶', 'paquete'],
    ['Toallitas de bebé', '👶', 'paquete'],
    ['Arena para gato', '🐈', 'bolsa'],
    ['Bolsas para perro', '🐕', 'rollo'],
    ['Premios para mascotas', '🐾', 'bolsa'],
    ['Pilas', '🔋', 'pack'],
  ]),
  ...group('other', [
    ['Leche infantil', '🍼', 'bote'],
    ['Papilla infantil', '🥣', 'caja'],
    ['Potitos', '👶', 'bote'],
  ]),
];
export const starterLists = [
  {
    name: 'Compra semanal',
    nameEn: 'Weekly shop',
    emoji: '🥑',
    color: 'sage',
    names: ['Tomates', 'Plátanos', 'Aguacate', 'Leche', 'Huevos', 'Pan', 'Arroz', 'Pollo'],
  },
  {
    name: 'Desayunos felices',
    nameEn: 'Happy breakfasts',
    emoji: '🥐',
    color: 'butter',
    names: ['Café', 'Leche', 'Pan', 'Huevos', 'Yogur natural', 'Avena', 'Plátanos'],
  },
  {
    name: 'Casa a punto',
    nameEn: 'Home essentials',
    emoji: '🧼',
    color: 'blue',
    names: ['Papel higiénico', 'Detergente', 'Lavavajillas', 'Bolsas de basura', 'Gel de ducha'],
  },
  {
    name: 'Noche de pasta',
    nameEn: 'Pasta night',
    emoji: '🍝',
    color: 'peach',
    names: ['Pasta', 'Tomate frito', 'Queso', 'Champiñones', 'Aceite de oliva'],
  },
];
